#!/bin/bash
# vim: set ft=sh

set -e

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

source $(dirname $0)/common.sh

destination=$1

if [ -z "$destination" ]; then
  echo "usage: $0 <path/to/destination>" >&2
  exit 1
fi

# for jq
PATH=/usr/local/bin:$PATH

payload=$(mktemp $TMPDIR/git-resource-request.XXXXXX)

cat > $payload <&0

load_pubkey $payload
configure_git_ssl_verification $payload

uri=$(jq -r '.source.uri // ""' < $payload)
branch=$(jq -r '.source.branch // ""' < $payload)
ref=$(jq -r '.version.ref // "HEAD"' < $payload)
depth=$(jq -r '(.params.depth // 0)' < $payload)
fetch=$(jq -r '(.params.fetch // [])[]' < $payload)
submodules=$(jq -r '(.params.submodules // "all")' < $payload)

[[ -z "$fetch" ]] && single_branch_flag="--single-branch " || single_branch_flag=''

if [ -z "$uri" ]
then
  echo "invalid payload (missing uri):" >&2
  cat $payload >&2
  exit 1
fi

echo "$ref"

# Strip any extra multi-branch refs
original_ref="$ref"
ref="${ref%%:*}"

ref_extras=":${original_ref#*:}"
if [ "$ref_extras" = ":$original_ref" ]
then
  ref_extras=""
else
  ref_and_branch="${original_ref%% *}"
  branch="${ref_and_branch##*:}"
fi

branchflag=""
if [ -n "$branch" ]
then
  branchflag="--branch $branch"
fi

depthflag=""
if test "$depth" -gt 0 2> /dev/null
then
  depthflag="--depth $depth"
fi

echo "Cloning: git clone ${single_branch_flag}$depthflag $uri $branchflag $destination"
git clone ${single_branch_flag}${depthflag} $uri $branchflag $destination

cd $destination

git checkout -q $ref
git log -1 --oneline
git clean --force --force -d
if [[ -n "$branch" ]] 
then
  git config --local concourse-ci.branch-name $branch
fi

if [ "$submodules" == "all" ]
then
  git submodule update --init  $depthflag --recursive
elif [ "$submodules" != "none" ]
then
  submodules=$(echo $submodules | jq -r '(.[])')
  for submodule in $submodules
  do
    git submodule update --init $depthflag --recursive $submodule
  done
fi

for branch in $fetch
do
  if [ -z "$(git branch --list $branch)" ] ; then
    git fetch origin $branch
    git branch $branch FETCH_HEAD
  fi
done

new_ref="$(echo "$(git rev-parse HEAD)$ref_extras" | jq -R .)"
jq -n "{
  version: {ref: $new_ref},
  metadata: $(git_metadata)
}" >&3
